#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TheDaedalusSentenceCompanion.Droid.Resource", IsApplication=true)]

namespace TheDaedalusSentenceCompanion.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int diespecial1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int diespecial2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int diespecial3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int diespecial4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int diespecial5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int diespecial6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dietheseus1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dietheseus2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dietheseus3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dietheseus4 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dietheseus5 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dietheseus6 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dietimer1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dietimer2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dietimer3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dietimer4 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dietimer5 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int dietimer6 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int logodaedalus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int splash = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
