// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TheDaedalusSentenceCompanion {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_nl {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_nl() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TheDaedalusSentenceCompanion.AppResources.nl", typeof(AppResources_nl).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ChooseYourEscapePlan {
            get {
                return ResourceManager.GetString("ChooseYourEscapePlan", resourceCulture);
            }
        }
        
        public static string SecondTimeThrough {
            get {
                return ResourceManager.GetString("SecondTimeThrough", resourceCulture);
            }
        }
        
        public static string Veteran {
            get {
                return ResourceManager.GetString("Veteran", resourceCulture);
            }
        }
        
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        public static string HellInSpace {
            get {
                return ResourceManager.GetString("HellInSpace", resourceCulture);
            }
        }
        
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string RepairsImminent {
            get {
                return ResourceManager.GetString("RepairsImminent", resourceCulture);
            }
        }
        
        public static string RepairsImminentDesc {
            get {
                return ResourceManager.GetString("RepairsImminentDesc", resourceCulture);
            }
        }
        
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        public static string AutomatedSecuritySystems {
            get {
                return ResourceManager.GetString("AutomatedSecuritySystems", resourceCulture);
            }
        }
        
        public static string AutomatedSecuritySystemsDesc {
            get {
                return ResourceManager.GetString("AutomatedSecuritySystemsDesc", resourceCulture);
            }
        }
        
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        public static string RollingLockdowns {
            get {
                return ResourceManager.GetString("RollingLockdowns", resourceCulture);
            }
        }
        
        public static string RollingLockdownsDesc {
            get {
                return ResourceManager.GetString("RollingLockdownsDesc", resourceCulture);
            }
        }
        
        public static string EmergencyProtocols {
            get {
                return ResourceManager.GetString("EmergencyProtocols", resourceCulture);
            }
        }
        
        public static string EmergencyProtocolsDesc {
            get {
                return ResourceManager.GetString("EmergencyProtocolsDesc", resourceCulture);
            }
        }
        
        public static string FaultyAlgorithm {
            get {
                return ResourceManager.GetString("FaultyAlgorithm", resourceCulture);
            }
        }
        
        public static string FaultyAlgorithmDesc {
            get {
                return ResourceManager.GetString("FaultyAlgorithmDesc", resourceCulture);
            }
        }
        
        public static string StartYourEscape {
            get {
                return ResourceManager.GetString("StartYourEscape", resourceCulture);
            }
        }
        
        public static string RoundTime {
            get {
                return ResourceManager.GetString("RoundTime", resourceCulture);
            }
        }
        
        public static string TimeToEscape {
            get {
                return ResourceManager.GetString("TimeToEscape", resourceCulture);
            }
        }
        
        public static string StartRound {
            get {
                return ResourceManager.GetString("StartRound", resourceCulture);
            }
        }
        
        public static string EndRound {
            get {
                return ResourceManager.GetString("EndRound", resourceCulture);
            }
        }
        
        public static string MadeIt {
            get {
                return ResourceManager.GetString("MadeIt", resourceCulture);
            }
        }
        
        public static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        public static string Escaped {
            get {
                return ResourceManager.GetString("Escaped", resourceCulture);
            }
        }
        
        public static string EscapedDescription {
            get {
                return ResourceManager.GetString("EscapedDescription", resourceCulture);
            }
        }
        
        public static string Captured {
            get {
                return ResourceManager.GetString("Captured", resourceCulture);
            }
        }
        
        public static string CapturedDescription {
            get {
                return ResourceManager.GetString("CapturedDescription", resourceCulture);
            }
        }
        
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string RerollDice {
            get {
                return ResourceManager.GetString("RerollDice", resourceCulture);
            }
        }
    }
}
